### ISSUE TITLE
[PE-D][Tester D] Broken link to glossary

### ISSUE THREAD

**Issue by nus-se-script** [AY2425S1-CS2103T-F12-3/tp#356]
After clicking the hyperlink to glossary, it sends me to FAQ

-------------
Labels: `severity.VeryLow` `type.DocumentationBug`
original: yuvrajaryan/ped#1

**Comment by yong-zhuo** [comment]
After checking the User Guide on our website, all the links are working fine. However, in the pdf version for the user guide, it seemed that the links will bring the reader to some where near the section but not exactly at the start of the section

This might be due to printing the pdf file at 75% scale. After printing out the UG at default scale, the links work fine but the page breaks and table formatting for parameter details will look awkward.
